### ISSUE TITLE
Creating a tag page for a nested tag doesn't work

### ISSUE THREAD

**Issue by mjsumpter** [mjsumpter/obsidian-tag-page#20]
When trying to create a tag page for a nested tag _only_ (no wildcard, `#tag/*`), the plugin fails.

See #19 for details

**Comment by duckfarts** [comment]
I'm also experiencing issues creating tag pages for nested tags, but I noticed that if you create a tag page (using a root level tag) and then you change the `tag-page-query` property to a nested tag, the page populates fine.

My _guess_ is that **making tag pages might not be working because nested tags have `/` characters in them, and those can't be used for the name of a page**; maybe the `/` characters need to be replaced?

**Comment by mjsumpter** [comment]
@duckfarts Solid idea, you may be right. I'll look into that.

**Comment by duckfarts** [comment]
So I was poking around the .js code and found how to fix this, and stumbled upon how to make a pull request for this (I am new to using git so I'm clicking and guessing).
